### ISSUE TITLE
Robot_operation_supportのビルドについて

### ISSUE THREAD

**Issue by Nobu19800** [Y-Yamamoto0/Robot_operation_support#1]
Robot_operation_supportのCMakeLists.txtに`find_package(OpenCV)`等のOpenCVに関する設定がないのでビルドできないのですが、何かマニュアルに書いていない手順があれば教えていただけないでしょうか。

**Comment by Y-Yamamoto0** [comment]
ご質問ありがとうございます。
私はVisual Studio上でRobot_operation_support→プロパティ→リンカー→追加の依存ファイルにOpenCVのライブラリを追加することにより、OpenCVを利用していました。
先ほどRobot_operation_support/Robot_operation_support/src/CMakeLists.txtを編集し、リンカーの設定を行わずにOpenCVを利用できる状態にいたしました。
ご迷惑をおかけいたしました。

**Comment by Nobu19800** [comment]
対応していただいてありがとうございます。issueは閉じます。
